### ISSUE TITLE
I can't run patches.

### ISSUE THREAD

**Issue by MarioNietoWorld** [SoundStacks/cmajor#3]
Hello, I am following the steps to configure cmajor, the problem is that when I run an example or create a new project, it does not show the gui or play any sound. I have installed cmajor VS extension, created a newProject "Annoying Beep" and in terminal VS I have run (and also test it with other example .cmajorpatchs):

cmaj play Annoying Beep/Annoying Beep.cmajorpatch

then I get this message in the terminal:
MIDI In Opening: Komplete Kontrol A DAW
MIDI input opening: KOMPLETE KONTROL A25 MIDI

nothing happens in any case. no GUI or sound.

the docs say:
"You should then hear a sine wave."

Among other things it is possible that something is wrong with the audio config. But I have no idea why the UI is not displayed when the patch I run have UI components.

thank you.

**Comment by cesaref** [comment]
Hi - can I confirm which host you are running on?

There are a few things odd about this output - you did not mention seeing any audio device listed on the output. I'd expect to see this is as the first two lines of output when running cmaj play, such as this example (running on a windows machine here):

> cmaj play .\Freeverb.cmajorpatch
Audio device: Remote Audio (Windows Audio)
44100Hz, 441 frames, latency: 10ms, output channels: (0, 1), input channels: (none)
Opening MIDI output: Microsoft GS Wavetable Synth
Loading: Freeverb.cmajorpatch
Loaded: Freeverb

Are the midi messages the complete output you see from the command?

Another way of running the generated patch from within VSCode is to press F5 with the .cmajorpatch file open. This will start the patch within an integrated terminal of VSCode, and this also helpfully shows the output level as a level bar, so if the patch is running, but no audio is audible, this will help show that the patch itself is running and that the issue is an audio device configuration problem.

**Comment by MarioNietoWorld** [comment]
Hi Cesaref, sorry I forgot to mention that I am on Windows 10.
I can confirm that I can load patches into a DAW (Ableton) using the VST3 you provide, so I can experiment with dragging and dropping  .cmajorpatch files into the plugin.

My first intention was to run a patch without opening a DAW, but didnt work, also when I press F5 inVSCode with the .cmajorpatch file open I get the following message:

"Filed to launch Cmajor server process!"

Anyway thanks for the response, using the plugin I can start experimenting.
